language: ruby
before_install:
- gem install asciidoctor tilt
script:
  - TEST = `python -c "import yaml; print yaml.load(open('metadata.yml','r').read())['_version']"`
  - echo $TEST
  # - git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
  # - asciidoctor -a toc -b xhtml5 -d book -T ./asciidoctor-htmlbook/htmlbook-autogen/
  # -d book Adventures-of-Huckleberry-Finn.asciidoc -o Adventures-of-Huckleberry-Finn.html

  # - git clone https://github.com/gitenberg-dev/HTMLBook
  # - xsltproc -stringparam external.assets.list " " ./HTMLBook/htmlbook-xsl/epub.xsl
  #   Adventures-of-Huckleberry-Finn.html
  # - cp ./HTMLBook/stylesheets/epub/epub.css OEBPS
  # - cp cover.png OEBPS/cover.png
  # - mv ./images ./OEBPS/
  # - zip -rX Adventures-of-Huckleberry-Finn.epub mimetype
  # - zip -rX Adventures-of-Huckleberry-Finn.epub OEBPS/ META-INF/
  # - zip -rX Adventures-of-Huckleberry-Finn.epub OEBPS/images/
addons:
  apt:
    packages:
    - xsltproc
